### ISSUE TITLE
App should parse the grade levels from the PDF.

### ISSUE THREAD

**Issue by jasonsreynolds** [freeCodeCamp/child-first-authority#1]

**Comment by cjsheets** [comment]
We established a branch-release convention and are targeting to have this feature integrated into v1.1.0 and deployed to a staging Heroku dyno.

We're currently going over the server and client implementations to find affected components. Prior to deploying the feature in production we'll need to ensure a data backup and recovery plan is in place.

**Comment by cjsheets** [comment]
First deployment resulted in a parser that would add grade levels to new students but not update existing students. We're currently working on fixing that behavior and improving the testing methods to avoid similar issues in the future

**Comment by rheajt** [comment]
I have pushed a fix to the v1.1.0 heroku dyno, but I don't have enough sample pdfs to really test how it is working. I am going to find a way to figure out a way to create better sample data.

**Comment by rheajt** [comment]
I am closing this issue since it is fixed on the v1.1.0 branch
